# Generated by Django 3.2.4 on 2021-06-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry',
        ),
    ]
