# Generated by Django 3.2.4 on 2021-06-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20210614_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='topics.topic'),
            preserve_default=False,
        ),
    ]
