# Generated by Django 3.2.4 on 2021-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(default='topic', max_length=50),
        ),
    ]
